window.pageTranslations = {
  sr: {
    page_title: "",
    s_text_1: "",
    s_title_2: "Naše usluge obuhvataju:",
    s_subtitle_2: "",
    s_text_2: "",
    s_subtitle_3: "",
    s_text_3: "",
    s_subtitle_4: "",
    s_text_4: "",
    s_subtitle_5: "",
    s_text_5: "",
    s_subtitle_6: "",
    s_text_6: "",
    s_subtitle_7: "",
    s_text_7: "",
    service_list_text_1: "",
    service_list_text_2: "",
    service_list_text_3: "",
    service_list_text_4: "",
    service_list_text_5: "",
    service_list_text_6: "",
    service_text_bottom: ""
  },
  en: {
    page_title: "",
    s_text_1: "",
    s_title_2: "Our services include:",
    s_subtitle_2: "",
    s_text_2: "",
    s_subtitle_3: "",
    s_text_3: "",
    s_subtitle_4: "",
    s_text_4: "",
    s_subtitle_5: "",
    s_text_5: "",
    s_subtitle_6: "",
    s_text_6: "",
    s_subtitle_7: "",
    s_text_7: "",
    service_list_text_1: "",
    service_list_text_2: "",
    service_list_text_3: "",
    service_list_text_4: "",
    service_list_text_5: "",
    service_list_text_6: "",
    service_text_bottom: ""
  }
}
